### PR TITLE
Fixing feedback

### PR DESCRIPTION
**Pull request by evelinec**
- Addressed additional comments from #40

### CODE REVIEW

**Comment by yeekangc** [comment]
@evelinec, IMHO, it's better not to change the "You need"s than to change them.  The original seems better and we can work with ID etc to revise later.

**Comment by yeekangc** [comment]
I will make a pass through this PR.

**Comment by yeekangc** [comment]
@evelinec, can you please explain why we are switching from creating a server.xml to not create one?  Thank you.

**Comment by evelinec** [comment]
> @evelinec, IMHO, it's better not to change the "You need"s than to change them. The original seems better and we can work with ID etc to revise later.

EC: I did add some words like, "is required". The other "You need"'s are still there.

**Comment by evelinec** [comment]
> @evelinec, can you please explain why we are switching from creating a server.xml to not create one? Thank you.

EC: @gkwan-ibm mentioned that it's better to have a working application before user starts developing the tests. His preference is to provide the `server.xml`. @gkwan-ibm can add additional comment if you have. @yeekangc you also mentioned a comment in issue #40 that " Doesn't mean that we have to create or replace. We should write it in a way that call out and inform users what they need to do. We didn't." I changed it back to providing the `server.xml` file, and added a sentence for direct user's attention to this file and the descriptions of features needed for Arquillian tests.

**Pull request merged**
